### PR TITLE
Make the pwa the master and default branch

### PR DESCRIPTION
**Pull request by nashpb**
As you can see, I have added manifest.json and icons to this branch which is kind of already makes the web app PWA. Go through the files again to check!

### CODE REVIEW

**Review by knnan — APPROVED** [review]
looks good

**Comment by praneshsingha** [comment]
👍

**Review by praneshsingha — APPROVED** [review]
👍

**Comment by lucy1281998** [comment]
Nishad I am not getting any things.

**Review by lucy1281998 — APPROVED** [review]

**Pull request merged**
